# Generated by Django 4.2.7 on 2023-12-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0004_alter_sandchanges_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandchanges',
            name='day_of_week',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
